# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Network_Sniffer
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -lx64/Packet \
    -lx64/wpcap \
    -lws2_32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = Network_Sniffer.rc
